### ISSUE TITLE
Nvidia.TextureTools throws EntryPointNotFoundException on Linux

### ISSUE THREAD

**Issue by Schala** [Mono-Game/MonoGame.Dependencies#5]
I've used the provided .so libraries, but upon trying to process a spritefont, MGCB throws the following:

```
Detected Linux using DXT Compression
System.EntryPointNotFoundException: nvttSetOutputOptionsOutputHandler
  at (wrapper managed-to-native) Nvidia.TextureTools.OutputOptions:nvttSetOutputOptionsOutputHandler (intptr,intptr,intptr)
  at Nvidia.TextureTools.OutputOptions.SetOutputHandler (Nvidia.TextureTools.ImageDelegate beginImage, Nvidia.TextureTools.WriteDataDelegate writeImage) [0x00000] in <filename unknown>:0
  at Microsoft.Xna.Framework.Content.Pipeline.Graphics.GraphicsUtil.CompressDxt (Microsoft.Xna.Framework.Content.Pipeline.Graphics.TextureContent content, Boolean generateMipmaps) [0x00000] in <filename unknown>:0
  at Microsoft.Xna.Framework.Content.Pipeline.Graphics.GraphicsUtil.CompressTexture (Microsoft.Xna.Framework.Content.Pipeline.Graphics.TextureContent content, Microsoft.Xna.Framework.Content.Pipeline.ContentProcessorContext context, Boolean generateMipmaps, Boolean premultipliedAlpha) [0x00000] in <filename unknown>:0
  at Microsoft.Xna.Framework.Content.Pipeline.Processors.FontDescriptionProcessor.Process (Microsoft.Xna.Framework.Content.Pipeline.Graphics.FontDescription input, Microsoft.Xna.Framework.Content.Pipeline.ContentProcessorContext context) [0x00000] in <filename unknown>:0
```

A resulting .xnb file is generated, but due to its small size compared to the successfully generated ones from PNG files, it may be corrupted.

**Comment by cra0zy** [comment]
So.. there are 2 nvtt errors:
1) Complaining about missing nvtt
2) System.EntryPointNotFoundException: nvttSetOutputOptionsOutputHandler

**Comment by cra0zy** [comment]
https://code.google.com/p/nvidia-texture-tools/source/browse/branches/2.0/project/vc8/Nvidia.TextureTools/TextureTools.cs?r=1096

**Comment by cra0zy** [comment]
This can be closed, fixed in #53

**Comment by theprophet31337** [comment]
I'm still having this issue with MonoGame Pipeline Tool 3.4.0.456 (that is the version from the about but the package version says 3.3-1) on linux (Netrunner 16 which is Kubuntu based) is that normal?

```home/virtue/prog/mono_workspace/ForgottenSchism/ForgottenSchism/Content/font/arial12norm.spritefont
Building Font /usr/share/fonts/truetype/msttcorefonts/Arial.ttf
Using DXT Compression
System.EntryPointNotFoundException: nvttSetOutputOptionsOutputHandler
  at (wrapper managed-to-native) Nvidia.TextureTools.OutputOptions:nvttSetOutputOptionsOutputHandler (intptr,intptr,intptr)
  at Nvidia.TextureTools.OutputOptions.SetOutputHandler (Nvidia.TextureTools.ImageDelegate beginImage, Nvidia.TextureTools.WriteDataDelegate writeImage) [0x00000] in <filename unknown>:0 
  at Microsoft.Xna.Framework.Content.Pipeline.Graphics.GraphicsUtil.CompressDxt (GraphicsProfile profile, Microsoft.Xna.Framework.Content.Pipeline.Graphics.TextureContent content, Boolean generateMipmaps, Boolean premultipliedAlpha, Boolean sharpAlpha) [0x00000] in <filename unknown>:0 
  at Microsoft.Xna.Framework.Content.Pipeline.Graphics.GraphicsUtil.CompressTexture (GraphicsProfile profile, Microsoft.Xna.Framework.Content.Pipeline.Graphics.TextureContent content, Microsoft.Xna.Framework.Content.Pipeline.ContentProcessorContext context, Boolean generateMipmaps, Boolean premultipliedAlpha, Boolean sharpAlpha) [0x00000] in <filename unknown>:0 
  at Microsoft.Xna.Framework.Content.Pipeline.Processors.FontDescriptionProcessor.Process (Microsoft.Xna.Framework.Content.Pipeline.Graphics.FontDescription input, Microsoft.Xna.Framework.Content.Pipeline.ContentProcessorContext context) [0x00000] in <filename unknown>:0 ```

**Comment by cra0zy** [comment]
It's only fixed in the develop branch, the fix is gonna be in MonoGame 3.5
